<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseAppHost>false</UseAppHost>
    <UserSecretsId>12682d01-1f75-42b8-b914-1f9226f506b5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\CrawlScope.Application\CrawlScope.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\CrawlScope.Infrastructure\CrawlScope.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\CrawlScope.Persistence\CrawlScope.Persistence.csproj" />
  </ItemGroup>

</Project>
